import {
  defineField,
  defineType,
} from "sanity";

export const eventRegistrationType =
  defineType({
    name:
      "eventRegistration",

    title:
      "Event Registration",

    type:
      "document",

    fields: [
      defineField({
        name: "event",
        title: "Event",
        type: "reference",

        to: [
          {
            type: "event",
          },
        ],

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "status",
        title: "Status",
        type: "string",

        options: {
          list: [
            {
              title:
                "Confirmed",
              value:
                "confirmed",
            },

            {
              title:
                "Waitlist",
              value:
                "waitlist",
            },

            {
              title:
                "Cancelled",
              value:
                "cancelled",
            },

            {
              title:
                "Checked in",
              value:
                "checked-in",
            },
          ],

          layout:
            "dropdown",
        },

        initialValue:
          "confirmed",

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name:
          "registeredAt",

        title:
          "Registered At",

        type:
          "datetime",

        initialValue: () =>
          new Date()
            .toISOString(),

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "firstName",

        title:
          "First Name",

        type: "string",

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "lastName",

        title:
          "Last Name",

        type: "string",

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "email",

        title: "Email",

        type: "string",

        validation: (Rule) =>
          Rule
            .required()
            .email(),
      }),

      defineField({
        name:
          "university",

        title:
          "University / School",

        type: "string",

        description:
          "Optional. For example VŠE.",
      }),

      defineField({
        name: "note",

        title:
          "Registration Note",

        type: "text",

        rows: 3,

        description:
          "Optional note from the attendee.",
      }),

      defineField({
        name:
          "ticketCode",

        title:
          "Ticket Code",

        type:
          "string",

        readOnly: true,

        description:
          "Unique ticket identifier generated by the website.",
      }),

      /*
        EMAIL INFO
      */

      defineField({
        name:
          "confirmationEmailSentAt",

        title:
          "Confirmation Email Sent At",

        type:
          "datetime",

        readOnly: true,
      }),

      defineField({
        name:
          "confirmationEmailId",

        title:
          "Confirmation Email ID",

        type:
          "string",

        readOnly: true,
      }),

      /*
        CHECK-IN
      */

      defineField({
        name:
          "checkedInAt",

        title:
          "Checked In At",

        type:
          "datetime",

        readOnly: true,
      }),
    ],

    preview: {
      select: {
        firstName:
          "firstName",

        lastName:
          "lastName",

        email:
          "email",

        eventTitle:
          "event.title",

        status:
          "status",
      },

      prepare({
        firstName,
        lastName,
        email,
        eventTitle,
        status,
      }) {
        const statusLabel =
          status ===
          "checked-in"
            ? "✓ Checked in"
            : status ===
                "confirmed"
              ? "Confirmed"
              : status ===
                  "waitlist"
                ? "Waitlist"
                : status ===
                    "cancelled"
                  ? "Cancelled"
                  : status;

        return {
          title:
            `${firstName ?? ""} ${lastName ?? ""}`.trim() ||
            email ||
            "Registration",

          subtitle: [
            eventTitle,
            statusLabel,
            email,
          ]
            .filter(Boolean)
            .join(" · "),
        };
      },
    },
  });