import {
  defineField,
  defineType,
} from "sanity";

export const eventRegistrationType =
  defineType({
    name:
      "eventRegistration",

    title:
      "Event Registration",

    type:
      "document",

    fields: [
      defineField({
        name: "event",
        title: "Event",
        type: "reference",

        to: [
          {
            type: "event",
          },
        ],

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "status",
        title: "Status",
        type: "string",

        options: {
          list: [
            {
              title:
                "Pending payment",
              value:
                "pending-payment",
            },

            {
              title:
                "Confirmed",
              value:
                "confirmed",
            },

            {
              title:
                "Waitlist",
              value:
                "waitlist",
            },

            {
              title:
                "Cancelled",
              value:
                "cancelled",
            },

            {
              title:
                "Checked in",
              value:
                "checked-in",
            },
          ],

          layout:
            "dropdown",
        },

        initialValue:
          "confirmed",

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name:
          "registeredAt",

        title:
          "Registered At",

        type:
          "datetime",

        initialValue: () =>
          new Date()
            .toISOString(),

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "firstName",

        title:
          "First Name",

        type: "string",

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "lastName",

        title:
          "Last Name",

        type: "string",

        validation: (Rule) =>
          Rule.required(),
      }),

      defineField({
        name: "email",

        title: "Email",

        type: "string",

        validation: (Rule) =>
          Rule
            .required()
            .email(),
      }),

      defineField({
        name:
          "university",

        title:
          "University / School",

        type: "string",

        description:
          "Optional. For example VŠE.",
      }),

      defineField({
        name: "note",

        title:
          "Registration Note",

        type: "text",

        rows: 3,

        description:
          "Optional note from the attendee.",
      }),

      defineField({
        name:
          "ticketCode",

        title:
          "Ticket Code",

        type:
          "string",

        readOnly: true,

        description:
          "Unique ticket identifier generated by the website.",
      }),

      /*
        PAYMENT
      */

      defineField({
        name:
          "paymentStatus",

        title:
          "Payment Status",

        type:
          "string",

        options: {
          list: [
            {
              title:
                "Not required",
              value:
                "not_required",
            },

            {
              title:
                "Pay on site",
              value:
                "pay_on_site",
            },

            {
              title:
                "Pending",
              value:
                "pending",
            },

            {
              title:
                "Paid",
              value:
                "paid",
            },

            {
              title:
                "Failed",
              value:
                "failed",
            },

            {
              title:
                "Refunded",
              value:
                "refunded",
            },
          ],

          layout:
            "dropdown",
        },

        readOnly: true,

        description:
          "Payment state managed automatically by the website.",
      }),

      defineField({
        name:
          "paymentProvider",

        title:
          "Payment Provider",

        type:
          "string",

        readOnly: true,

        description:
          "Payment provider used for this registration.",
      }),

      defineField({
        name:
          "paymentTransactionId",

        title:
          "Comgate Transaction ID",

        type:
          "string",

        readOnly: true,

        description:
          "Transaction identifier returned by Comgate.",
      }),

      defineField({
        name:
          "paymentRedirectUrl",

        title:
          "Payment Redirect URL",

        type:
          "url",

        readOnly: true,

        description:
          "Checkout URL returned by Comgate.",
      }),

      defineField({
        name:
          "paymentAmount",

        title:
          "Payment Amount",

        type:
          "number",

        readOnly: true,

        description:
          "Amount charged in CZK. Stored as a snapshot of the event price.",
      }),

      defineField({
        name:
          "paymentCurrency",

        title:
          "Payment Currency",

        type:
          "string",

        readOnly: true,

        description:
          "Currency used for the payment.",
      }),

      defineField({
        name:
          "paymentCreatedAt",

        title:
          "Payment Created At",

        type:
          "datetime",

        readOnly: true,
      }),

      defineField({
        name:
          "reservationExpiresAt",

        title:
          "Seat Reservation Expires At",

        type:
          "datetime",

        readOnly: true,

        description:
          "Until this time, a pending payment temporarily reserves a seat.",
      }),

      defineField({
        name:
          "paidAt",

        title:
          "Paid At",

        type:
          "datetime",

        readOnly: true,
      }),

      defineField({
        name:
          "refundedAt",

        title:
          "Refunded At",

        type:
          "datetime",

        readOnly: true,
      }),

      /*
        EMAIL INFO
      */

      defineField({
        name:
          "confirmationEmailSentAt",

        title:
          "Confirmation Email Sent At",

        type:
          "datetime",

        readOnly: true,
      }),

      defineField({
        name:
          "confirmationEmailId",

        title:
          "Confirmation Email ID",

        type:
          "string",

        readOnly: true,
      }),

      /*
        CHECK-IN
      */

      defineField({
        name:
          "checkedInAt",

        title:
          "Checked In At",

        type:
          "datetime",

        readOnly: true,
      }),
    ],

    preview: {
      select: {
        firstName:
          "firstName",

        lastName:
          "lastName",

        email:
          "email",

        eventTitle:
          "event.title",

        status:
          "status",

        paymentStatus:
          "paymentStatus",
      },

      prepare({
        firstName,
        lastName,
        email,
        eventTitle,
        status,
        paymentStatus,
      }) {
        const statusLabel =
          status ===
          "pending-payment"
            ? "Payment pending"
            : status ===
                "checked-in"
              ? "✓ Checked in"
              : status ===
                  "confirmed"
                ? "Confirmed"
                : status ===
                    "waitlist"
                  ? "Waitlist"
                  : status ===
                      "cancelled"
                    ? "Cancelled"
                    : status;

        const paymentLabel =
          paymentStatus ===
          "paid"
            ? "Paid"
            : paymentStatus ===
                "pay_on_site"
              ? "Pay on site"
              : paymentStatus ===
                  "pending"
                ? "Payment pending"
                : paymentStatus ===
                    "failed"
                  ? "Payment failed"
                  : paymentStatus ===
                      "refunded"
                    ? "Refunded"
                    : undefined;

        return {
          title:
            `${firstName ?? ""} ${lastName ?? ""}`.trim() ||
            email ||
            "Registration",

          subtitle: [
            eventTitle,
            statusLabel,
            paymentLabel,
            email,
          ]
            .filter(Boolean)
            .join(" · "),
        };
      },
    },
  });